### ISSUE TITLE
TSC errors in code

### ISSUE THREAD

**Issue by JulianHidalgo** [johnwargo/learning-pwa-code#1]
Hi!

First of all thanks for a great book :). I tried to run tsc on the code for chapter 03, but it failed with the errors I'm pasting next. I'm using TypeScript 3.4.5 to match the version in package.json. I tried a few different versions, but it didn't help.

app/routes/api.ts:79:17 - error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
79                 copy[attr] = clone(obj[attr]);
                   ~~~~~~~~~~
app/routes/api.ts:103:19 - error TS7006: Parameter 'result' implicitly has an 'any' type.
103             .then(result => {
                      ~~~~~~
app/routes/api.ts:175:20 - error TS7006: Parameter 'err' implicitly has an 'any' type.
175             .catch(err => {
                       ~~~
app/routes/api.ts:239:9 - error TS7017: Element implicitly has an 'any' type because type 'UserSentiment' has no index signature.
239         _userSentiment[sentiment] = _userSentiment[sentiment] + 1;
            ~~~~~~~~~~~~~~~~~~~~~~~~~
app/routes/api.ts:239:37 - error TS7017: Element implicitly has an 'any' type because type 'UserSentiment' has no index signature.
239         _userSentiment[sentiment] = _userSentiment[sentiment] + 1;

I fixed them by adding an indexer to UserSentiment:
export interface UserSentiment {
    [index: string]: number,
    amazing: number,
   // ...

Also adding parenthesis to the arguments of the then and catch statements:
 ".then(result: any =>" .then((result: any) => 

And I also had to ignore a line in the clone method in api.ts:
// @ts-ignore
copy[attr] = clone(obj[attr]);

Cheers,
Julián

**Comment by johnwargo** [comment]
Julián, Thanks for passing on the feedback. I know the TypeScript compiler calls those errors, but they're really not - they're just warnings and the file compiles just fine.  I'll clean this up and publish an update.

How is it you're reading the book already - did you buy the eBook or are you reading it on Safari Books online?

**Comment by JulianHidalgo** [comment]
Hey John!

They were thrown as errors in my case, but I didn't check if generated the output JS. I don't use TypeScript, but I was surprised because as I understood any JavaScript code would be valid TypeScript code too.

I have an O'Reilly subscription and the book is available there, I figured it was some kind of early access thing :D.
