### ISSUE TITLE
Bing API changes

### ISSUE THREAD

**Issue by WelchData** [johnwargo/learning-pwa-code#3]
Hi John, I just want to draw your attention to the changes in the Bing search api (the change from Cognitive Services to Bing Search Services) which you may very well be aware of.

Unfortunately this puts a major hitch in the follow along code from Chapter 3 - or at least I'm having trouble reconfiguring the code to match the new version of the API, or creating an olde style API. 

The book is still adding a great deal of value (thank you) and I'll no doubt be learning a lot trying to get passed the problem, I just wanted to let you know there is an issue.

Thanks, Chris.

**Comment by johnwargo** [comment]
@WelchData thanks for reaching out.   I saw the announcement from Microsoft about the API change, but I thought it would still be available for a couple of years. My plan was to update the code (and chapter content) as it got closer to the changeover, but apparently I have to do something about that sooner rather than then. I'll make a note and start digging into this in the next couple of weeks and publish the updated code here and content on the book's web site. Thanks for letting me know.

**Comment by johnwargo** [comment]
Rats, its more than a simple change. Sigh. I'll get to work on this and publish updated code. Unfortunately the affected code runs through several chapters. I'll get it done as soon as I can.

**Comment by WelchData** [comment]
Thanks John. Really appreciated. Looking forward to the update.

**Comment by johnwargo** [comment]
@WelchData I refactored the code to use the new API and wrote some simple docs for the new process. I'll test all of this and likely publish an `updated` folder to the repo.  You should be able to test this tomorrow. Can you help me validate the instructions?  I need a different set of eyes on it before other readers start to use it.

**Comment by WelchData** [comment]
@johnwargo - Not a problem. Would be great to help out.

**Comment by johnwargo** [comment]
@WelchData I published the updated code, please take a look. I just realized I needed to make some changes to the repo's readme which I haven't done yet. I'll do that now.

**Comment by WelchData** [comment]
@johnwargo  Chapter 3's code seems fine now, I've got a working app. The only issues that came up were with the type script compiler (see below). I'll get back to you on Chp 4 and Chp 5 as soon as I can.

Running the tsc command gave me these errors:

$ tsc
../../../../node_modules/@types/readable-stream/index.d.ts:13:15 - error TS2417: Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.
  The types of 'Stream.Readable.Writable' are incompatible between these types.
    Type 'typeof _Readable.Writable' is not assignable to type 'typeof import("stream").Writable'.
      Types of parameters 'options' and 'opts' are incompatible.
        Type 'import("stream").WritableOptions | undefined' is not assignable to type '_Readable.WritableOptions | undefined'.
          Type 'import("stream").WritableOptions' is not assignable to type '_Readable.WritableOptions'.
            Type 'WritableOptions' is not assignable to type 'WritableStateOptions'.
              Types of property 'defaultEncoding' are incompatible.
                Type 'string | undefined' is not assignable to type '"ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | undefined'.
                  Type 'string' is not assignable to type '"ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | undefined'.     

13 declare class _Readable extends stream.Readable {
                 ~~~~~~~~~

../../../../node_modules/@types/readable-stream/index.d.ts:62:11 - error TS2720: Class 'Duplex' incorrectly implements class '_Readable'. Did you mean to extend '_Readable' and inherit its members as a subclass?
  Type 'Duplex' is missing the following properties from type '_Readable': readableEncoding, readableEnded, readableFlowing

62     class Duplex extends Writable implements /*extends*/_Readable, stream.Duplex {
             ~~~~~~

../../../../node_modules/@types/readable-stream/index.d.ts:62:11 - error TS2720: Class '_Readable.Duplex' incorrectly implements class 'import("stream").Duplex'. Did you mean to extend 'import("stream").Duplex' and inherit its members as a subclass?
  Type 'Duplex' is missing the following properties from type 'Duplex': readableEncoding, readableEnded, readableFlowing

62     class Duplex extends Writable implements /*extends*/_Readable, stream.Duplex {
             ~~~~~~

../../../../node_modules/@types/readable-stream/index.d.ts:104:9 - error TS2416: Property '_transform' in type 'PassThrough' is not assignable to the same property in base type 'PassThrough'.
  Type '<T>(chunk: T, encoding: "ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | null | undefined, callback: (error: any, data: T) => void) => void' is not assignable to type '(chunk: any, encoding: string, callback: TransformCallback) => void'.
    Types of parameters 'encoding' and 'encoding' are incompatible.
      Type 'string' is not assignable to type '"ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | null | undefined'.

104         _transform<T>(chunk: T, encoding: BufferEncoding | null | undefined, callback: (error: any, data: T) => void): void;
            ~~~~~~~~~~

../../../../node_modules/@types/readable-stream/index.d.ts:163:11 - error TS2720: Class '_Readable.Transform' incorrectly implements class 'import("stream").Transform'. Did you mean to extend 'import("stream").Transform' and inherit its members as a subclass?
  Type 'Transform' is missing the following properties from type 'Transform': readableEncoding, readableEnded, readableFlowing

163     class Transform extends Duplex implements stream.Transform {

**Comment by johnwargo** [comment]
@WelchData I'm not experiencing that, but there's something weird about the output. So here's what I did:

+ Cloned the repo
+ navigated to the `chapter-03` folder
+ executed `npm install`
+ executed `tsc`

You can see the output here:

![image](https://user-images.githubusercontent.com/571463/98823973-b75f2d00-2400-11eb-9f98-a05cab39a88d.png)

What's weird about your output is this:

```text
../../../../node_modules/@types/readable-stream/index.d.ts:13:15
```

its referencing node types from deep in the folder structure which doesn't make sense. 

I'm assuming you're doing this on a mac?  I did mine on Windows, I'll try it on the mac and see what happens.

**Comment by johnwargo** [comment]
Similar experience on macOS with the same result. 

![image](https://user-images.githubusercontent.com/571463/98827326-bcbe7680-2404-11eb-8865-5946f6562292.png)

**Comment by WelchData** [comment]
Must be from my setup. I cloned the repo again and then just replaced the corresponding chapters. Suggests this is a non-issue then if you can't replicate it.

**Comment by WelchData** [comment]
@johnwargo I've been through chapters 4 and 5. All looks good from the API perspective. I couldn't get the same offline pages to show as in the text - that might just be user error though.

**Comment by johnwargo** [comment]
Of you don't mind, share the details with me. I don't want you to have issues and I don't want other readers to have them either.

**Comment by WelchData** [comment]
Sure. It started with the offline error message (~fig 4.7). The api results came through when I was offline instead of the 'no data' message so they seemed to already be cached. From that point on I didn't really get what I expected from the offline behaviour - but, that could just be user error...

**Comment by johnwargo** [comment]
Best way to tell is to look at the console, you should see what's happening under the covers there.

**Comment by johnwargo** [comment]
@WelchData did you get it to work?

**Comment by WelchData** [comment]
@johnwargo - Hi John, sorry for not updating. Apologies - had to move onto other things so didn't really get the chance to dig into the issue as much as I should. Pretty sure it was just user error though. You can definitely close out the issue if you'd like.
